NUMPY _INTRODUCTION 

In [ ]:
mylist=[1,2,3,4]

In [2]:
import numpy as np

In [3]:
arr=np.array(mylist)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.11317888, 0.75212768, 0.47158289, 0.78260896, 0.44724703])

In [14]:
np.random.rand(4,4)

array([[0.81201487, 0.54188811, 0.8634858 , 0.40563919],
       [0.21167601, 0.28810226, 0.38647595, 0.62607209],
       [0.84479114, 0.54125849, 0.44777031, 0.92934174],
       [0.20594529, 0.05733439, 0.32555284, 0.51195033]])

In [15]:
np.random.randn(2)

array([-0.45740991,  0.0837879 ])

In [16]:
np.random.randn(4,4)

array([[ 1.25909179,  1.42211746, -0.24419825,  0.77092541],
       [ 1.39608039, -1.48080601,  1.39823032, -0.83038428],
       [-0.21215423, -0.69721235,  1.86378421, -1.48168031],
       [-0.01380783, -0.26094066, -0.90301204, -0.07787287]])

In [17]:
np.random.randint(2,200)

31

In [18]:
np.random.randint(2,200,3)

array([110, 115, 119])

In [19]:
arr=np.arange(25)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr= np.random.randint(0,50,10)

In [22]:
ranarr

array([21, 12, 42, 18, 11, 33, 36,  1, 47, 42])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr

array([21, 12, 42, 18, 11, 33, 36,  1, 47, 42])

In [25]:
ranarr.max()

47

In [26]:
ranarr.min()

1

In [27]:
ranarr.argmax()

8

In [28]:
arr.dtype

dtype('int64')

NUMPY INDEXING

In [29]:
import numpy as np

In [30]:
ar=np.arange(0,11)

In [31]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
ar[8]

8

In [33]:
ar[1:5]

array([1, 2, 3, 4])

In [34]:
ar[0:5]

array([0, 1, 2, 3, 4])

In [35]:
ar[:6]

array([0, 1, 2, 3, 4, 5])

In [37]:
ar[5:]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
ar[0:5]=100

In [39]:
ar

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [40]:
slice=arr[0:6]

In [41]:
slice

array([0, 1, 2, 3, 4, 5])

In [42]:
slice[:]=99

In [43]:
slice

array([99, 99, 99, 99, 99, 99])

In [44]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
arr1=arr.copy()

In [46]:
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
arr1[:]=78

In [49]:
arr1

array([78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78,
       78, 78, 78, 78, 78, 78, 78, 78])

In [50]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr2d=np.array([[5,6,7],[7,9,8],[2,3,4]])

In [52]:
arr2d

array([[5, 6, 7],
       [7, 9, 8],
       [2, 3, 4]])

In [54]:
arr2d[0][2]


7

In [55]:
arr2d[0,2]

7

In [56]:
arr2d[:2,1:]

array([[6, 7],
       [9, 8]])

In [57]:
a1=np.arange(1,11)

In [58]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
bool_a1=a1>5

In [62]:
a1[bool_a1]

array([ 6,  7,  8,  9, 10])

In [63]:
a1[a1>5]

array([ 6,  7,  8,  9, 10])

In [64]:
b1=np.arange(50).reshape(5,10)

In [65]:
b1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

NUMPY OPERATIONS

In [66]:
a2=np.arange(11)

In [67]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
a2+a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [69]:
a2-a2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
a2*a2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [71]:
a2+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [72]:
a2*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [73]:
a2/a2

/tmp/ipykernel_90/3568982664.py:1: RuntimeWarning: invalid value encountered in divide
  a2/a2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [74]:
1/a2

/tmp/ipykernel_90/2660750406.py:1: RuntimeWarning: divide by zero encountered in divide
  1/a2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [75]:
a2 ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

NUMPY UNIVERSAL FUNCTIONS

In [76]:
np.sqrt(a2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [77]:
np.exp(a2)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [78]:
np.max(a2)

10

In [79]:
np.sin(a2)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [80]:
np.log(a2)

/tmp/ipykernel_90/970536687.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a2)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])